### ISSUE TITLE
1 time secret from server.

### ISSUE THREAD

**Issue by uwejan** [jas-/secStore.js#11]
Hi, am kindly asking for advice here, say my storage will get a 1 time secret key from server, how am i supposed to store/secure it, keep using the storage, without asking server for the key again?

**Comment by jas-** [comment]
That is actually outside the use case for this particular module. Also OTP and other derivatives are best left unsaved as they are typically used to derive a stronger symmetric key from.

While both are recommended an OTP or One Time Pad used to derive a key should almost never ever be saved and or re-used.

References for this can be found in NIST SP 800-63B.

Now that I have that out of the way, I would recommend researching the following topics; Transport layer security and security of at rest data with regards to protections that this piece of code will *assist* with as it is almost certainly NOT to be used as a *whole* security solution.

Hope that helps.
