### ISSUE TITLE
License

### ISSUE THREAD

**Issue by srbala** [jas-/secStore.js#5]
Is this project is released only under GPL?

is it possible on dual release with MIT or BSD?

**Comment by jas-** [comment]
No. Why?

**Comment by srbala** [comment]
Planning on using it in conjunction with SJCL, as per our legal team, not allowed to use GPL.

**Comment by jas-** [comment]
The GPL doesn't require you to open your code to the public. It requires any distributable project which makes use of this project as a component to include the source code and license.

**Comment by srbala** [comment]
Let me understand your angle of GPL ...

Since it is javascript library, when I include js file source is included. Based on your statement, if I include license file from this project along in my project, it satisfies GPL, and I dont have to open my code to public - Correct?

**Comment by jas-** [comment]
While I am not an IP lawyer, I know my interpretation of the [terms and conditions](https://en.wikipedia.org/wiki/GNU_General_Public_License#Terms_and_conditions) of the GPL with regards to unmodified usage and non- distribution of a project including any GPL'd code only requires the copyleft protections remain of the bundled GPL code.

**Comment by jas-** [comment]
@srbala I am going to close this as I am not going to change the license type. Have a good day.
