### ISSUE TITLE
localStorage with null values

### ISSUE THREAD

**Issue by MounicaChette** [jas-/secStore.js#6]
When ever i search for a local storage object which is null, i am getting the first local object from the storage.get method. Is this any kind of bug? Do we have a turn around for this?

**Comment by jas-** [comment]
In regards to your question about a turn around time; Patches for bugs are always appreciated.

I will need a use case to better evaluate your issue. Searching for 'null' will always produce unexpected results.

**Comment by MounicaChette** [comment]
I mean to say, when ever i search for a local storage object, which is never stored, then the get method returns the first object from local storage.
For example, lets assume i have a local storage object with key: "Test", i start searching for "Xyz", then what should be result of get method. In my case, the result of get method is the object with Key:"Test", which is not expected.

**Comment by MounicaChette** [comment]
Ok, now my issue is resolved, actually i was directly throwing the error from get method. and the console log i was having was that of the previous get method of a different key(In this example, the console log was showing the "Test" object).

**Comment by MounicaChette** [comment]
This piece of code have fixed my issue
if (ret) {
            ret = sjcl.decrypt(opts.passphrase, ret);
            ret = storage.toJSON(ret);

            if (ret) {
                cb(null, ret);
            } else {
                cb('Error occured retrieving storage data');
            }
        }
        else {
            cb('No storage data found for specified key.');
        }

**Comment by jas-** [comment]
Would you please provide a use case that triggered your problem?

**Comment by MounicaChette** [comment]
Accidentally, i was trying to get a storage object, which i did not set earlier. So the line of code gave "ret" as null: "ret = this[opts.storage] ? this[opts.storage].get(opts) :
          this.local.get(opts);"
Then with out null check on ret, the code was trying to decrypt ret object, which gave unexpected results. Hope this helps.

Also, i want to know the significance of passpharse. Is is something like private key used for encryption?

**Comment by jas-** [comment]
Ok so a complete use case would be very beneficial. When I say use case to replicate the issue you are experiencing I am referring to a complete piece of code you are using. If I am unable to replicate your issue then it makes it hard to address and resolve.

In regards to your question about the pass phrase option. It is provided in the documentation

**Comment by MounicaChette** [comment]
I have two different storage objects. 
1. userDetails
2. usersCount
I have set the local storage object for the first using the key "userDetails". 
Without setting(saving on web) the local storage for usersCount, i was trying to get that value using get method of secStore.js. There i was getting null reference exception and unexpected results.

**Comment by jas-** [comment]
Ok, that clarifies it. Thanks for the details, just wanted to make sure I could address a shortcoming and handling an exception regarding an order of operations problem warrants a fix. Thanks for reporting.
