### ISSUE TITLE
Storage preserves old values. Documentation lacks examples of how to update/delete data.

### ISSUE THREAD

**Issue by itbra** [jas-/secStore.js#7]
Hi, your usage examples appear somewhat incomplete because the don't mention the usage as a jQuery plugin. The README.md deployed describes the initialisation of the plugin as well as how to set and retrieve data. However, it lacks the info how to update/replace data.

Adapting the examples provided in the README.md I tried to update/replace/remove data like so:

```
// Initialisation:
jQuery(window).secStore({
   appID: 'MyApp',
   debug: true,
   data: {},
   callback: function(bool) {
      console.log('Saved:', bool);   // outputs 'false' because data is an empty object ... I suppose
   },
   errCallback: function(what, comes, in) {
      console.log('Error:', what, comes, in)   // Docs' missing information about the function parameters
   }
});

// Read 1:
jQuery(window).secStore({
   appID: 'MyApp',
   callback: function(data) {
      console.log('Read:', data);   // outputs 'false' because data is an empty object ... I suppose
   },
   errCallback: function(what, comes, in) {
      console.log('Error:', what, comes, in)   // Docs' missing information about the function parameters
   }
});

// Update data first try
jQuery(window).secStore({
   appID: 'MyApp',
   debug: true,
   data: {
      test1: 'success'
   },
   callback: function(bool) {
      console.log('Saved:', bool);   // outputs 'true' because data is not empty
   },
   errCallback: function(what, comes, in) {
      console.log('Error:', what, comes, in)   // Docs' missing information about the function parameters
   }
});

// Read 2:
jQuery(window).secStore({
   appID: 'MyApp',
   callback: function(data) {
      console.log('Read:', data);   // outputs '{test1: "success"}' as expected
   },
   errCallback: function(what, comes, in) {
      console.log('Error:', what, comes, in)   // Docs' missing information about the function parameters
   }
});

// Update data first try
jQuery(window).secStore({
   appID: 'MyApp',
   debug: true,
   data: {
      test1: null,
      test2: 'success too'
   },
   callback: function(bool) {
      console.log('Saved:', bool);   // outputs 'true' because data is not empty
   },
   errCallback: function(what, comes, in) {
      console.log('Error:', what, comes, in)   // Docs' missing information about the function parameters
   }
});

// Read3 :
jQuery(window).secStore({
   appID: 'MyApp',
   callback: function(data) {
      console.log('Read:', data);   // outputs '{test1: "success", test2: "success too"}' ... Huh?!? Why did it preserve old data instead of setting it null as requested?
   },
   errCallback: function(what, comes, in) {
      console.log('Error:', what, comes, in)   // Docs' missing information about the function parameters
   }
});

etc.
```

I expected the output of Read 3 to be either `'{test1: null, test2: "success too"}'` or `'{test2: "success too"}'` since I somewhat cleared `test1`. Instead the old value `success` has been stored again.
The debug output confirms that old data is re-stored which was not intended. Maybe you might clarify where my mistake is and how to set/update/delete data with your plugin the jQuery way?

**Comment by jas-** [comment]
I think your problem is with out dated examples; perhaps you should make use of the latest [documentation](https://github.com/jas-/secStore.js/blob/master/README.md).

Examples of the latest API is as follows;

Setting data ...
```javascript
var storage = new secStore
  , options = {
    encrypt: true,
    data: {
      key: 'some data that is somewhat private'
    }
  };

storage.set(options, function(err, results){
  if (err) throw err;
  console.log(results);
});
```

Getting data ...
```javascript
var storage = new secStore
  , options = {
    encrypt: true
  };

storage.get(options, function(err, results){
  if (err) throw err;
  console.log(results);
});
```

**Comment by itbra** [comment]
I did actually consult YOUR latest documentation here on site. However, following your guide and using your example above which is the same from your README I repeatedly end up with the error `Error: ReferenceError: secStore is not defined`. There seems to be no such class or object to instantiate. If I inspect my Javascript libraries file I can see this:
```
(function($){$.fn.secStore=function(method){
...
}})(jQuery)
```
This is in fact a jQuery plugin and requires to be initialized like is described in your deployed README.md. By the way, why is that README different from the introductory README here on Github? The deployed version mentions how to use your plugin the jQuery way. The version here does not. To me this appears to be somewhat unorganised and confusing and the reason why your script doesn't work. Thats why I ask you to sync your READMEs and provide working examples please.

**Comment by mario-rivera** [comment]
"However, it lacks the info how to update/replace data."
I ran across the same issue, in the jQuery version it is possible to update the keys by switching the order of the arguments on the save function. 

Around line 165: _storage.save

replace     $.extend(v, e);
with       $.extend(e, v);

**Comment by jas-** [comment]
I am closing this issue due to both instances using the outdated jQuery module provided with the bower installed repository.

Please use the `secstore.min.js` file vs. the jQuery one available from bower.
